grafana:
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      uid: Loki
      url: http://loki-monitoring.monitoring.svc.cluster.local:3100
      jsonData:
        maxLines: 5000
      isDefault: false
