loki:
  auth_enabled: false

  server:
    http_listen_port: 3100

  storage:
    type: azure
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    azure:
      accountName: lokistorageganesh
      accountKey: 6UHovZmb7irh74fhZvjJhIg7e3rd4ZxolTsE3cs4grQ2CnJFlcVycLQADBSRvqZiHNOYE8Iw+Gdc+ASta2Mpyg==

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: azure
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

# ✔️ Enable Prometheus monitoring for Loki
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false

  # ✔️ This creates ServiceMonitor so Prometheus can scrape Loki
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack   # VERY IMPORTANT
    interval: 30s
    scrapeTimeout: 10s

gateway:
  enabled: true
  service:
    type: LoadBalancer
