loki:
  config:
    schema_config:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      azure:
        account_name: lokistorageganesh
        account_key: O7HvlhjYcldzWnnvPLOI8zvCyJfZfv/C7S/F4LMK0AJt2335cfvqYjLvrz8VgVBXtVvMg5kaD+Rs+AStWQN/TA==
        container_name: loki
      boltdb_shipper:
        shared_store: azure

  persistence:
    enabled: true
    storageClassName: ganesh
    size: 10Gi
